.\" pcsxr(1) manual page
.Dd October 1, 2005
.Dt PCSXR 1
.Os
.\" ==================================================================
.Sh NAME
.Nm pcsxr
.Nd Playstation emulator
.\" ==================================================================
.Sh SYNOPSIS
.Nm
.Oo
.Ar options
.Oc
.Oo
.Ar file
.Oc
.\" ==================================================================
.Sh DESCRIPTION
PCSXR is a plugin-based PlayStation emulator able to play most PSX games.
It provides CPU, BIOS, and basic system emulation and relies on
plugins for sound, input, and graphics emulation.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl runcd
Runs CD-ROM from drive.
.It Fl cdfile Ar file
Runs a CD image file.
.It Fl nogui
Don't load the GUI.
.It Fl cfg Ar file
Specify a different config file.
.It Fl psxout
Enable PSX output.
.It Fl slowboot
Enable BIOS Logo.
.It Fl load Ar statenum
Loads savestate
.Ar statenum .
.It Fl help , Fl h
Display help message.
.El
.\" ==================================================================
.Sh AUTHORS
.An -nosplit
PCSX was written by
.An Linuzappz Aq Mt linuzappz@pcsx.net .
PCSX-df was written by
.An Ryan Schultz Aq Mt schultz.ryan@gmail.com and
.An Andrew Burton Aq Mt adb@iinet.net.au .
PCSX-Reloaded was written by
.An Wei Mingzhi Aq Mt weimingzhi@gmail.com .
.Pp
This manual page was written by
.An Alexandr Savca Aq Mt alexandr.savca89@gmail.com .
